# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 The Foundation for Public Code <info@publiccode.net>

title: Release Test
version: 0.0.0

remote_theme: publiccodenet/jekyll-theme
include:
  - "LICENSE"
