#!/bin/sh
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2021-2022 The Foundation for Public Code <info@publiccode.net>, https://standard.publiccode.net/AUTHORS

# This script is used to generate a PDF from the html generated by Jekyll.

# The 'serve.sh' script should be called prior to this script in order to
# create and serve html content on localhost:4000

weasyprint http://localhost:4000/index.html release-test.pdf --presentational-hints
