name: build-and-deploy
on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  ci-build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-deps
        # https://yaml.org/spec/1.2-old/spec.html#style/block/folded
        run: >
          sudo apt install -y
          ruby
          ruby-bundler
      - name: bundle-install
        run: bundle install
      - name: build
        run: bundle exec jekyll build --baseurl='/release-test'
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_site'
      - name: deploy-gh-pages
        id: deployment
        uses: actions/deploy-pages@v1
