name: release-on-tag
on:
  push:
    tags:
      - "*.*.*" # tag example: 0.4.1

defaults:
  run:
    shell: bash

jobs:
  release-the-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-deps
        # https://yaml.org/spec/1.2.2/#65-line-folding
        run: >
          sudo apt-get install -y
          ruby
          ruby-bundler
          fontconfig
          python3.10-venv
          python3-pip
      - name: bundle-install
        run: bundle install
      - name: install-fonts
        run: script/ensure-font.sh
      - name: build-pdf
        run: script/pdf.sh
      - name: link-change-latest
        run: ln -sv changelog/$(ls -1 changelog | sort | tail -n1) release.body
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: release-test-*.pdf
          body_path: release.body
